export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_SELECTED_CURRENCY = 'SET_SELECTED_CURRENCY';
export const SET_SELECTED_CURRENCY_SET = 'SET_SELECTED_CURRENCY_SET';
